import { Note } from './note';

export const keyboardNotes: Note[] = [
  {
    noteName: 'c',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'c',
    altAccidental: null,
  },
  {
    noteName: 'c#',
    octave: 4,
    keyColor: 'black',
    accidental: '#',
    noteStatus: 'incorrect',
    altNote: 'd',
    altAccidental: 'b',
  },
  {
    noteName: 'd',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'd',
    altAccidental: null,
  },
  {
    noteName: 'd#',
    octave: 4,
    keyColor: 'black',
    accidental: '#',
    noteStatus: 'incorrect',
    altNote: 'e',
    altAccidental: 'b',
  },
  {
    noteName: 'e',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'e',
    altAccidental: null,
  },
  {
    noteName: 'f',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'f',
    altAccidental: null,
  },
  {
    noteName: 'f#',
    octave: 4,
    keyColor: 'black',
    accidental: '#',
    noteStatus: 'incorrect',
    altNote: 'g',
    altAccidental: 'b',
  },
  {
    noteName: 'g',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'g',
    altAccidental: null,
  },
  {
    noteName: 'g#',
    octave: 4,
    keyColor: 'black',
    accidental: '#',
    noteStatus: 'incorrect',
    altNote: 'a',
    altAccidental: 'b',
  },
  {
    noteName: 'a',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'a',
    altAccidental: null,
  },
  {
    noteName: 'a#',
    octave: 4,
    keyColor: 'black',
    accidental: '#',
    noteStatus: 'incorrect',
    altNote: 'b',
    altAccidental: 'b',
  },
  {
    noteName: 'b',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'b',
    altAccidental: null,
  },
  {
    noteName: 'c',
    octave: 5,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'c',
    altAccidental: null,
  },
];

// export const keyboardNotesFlat: Note[] = [
//   {
//     noteName: 'c',
//     octave: 4,
//     keyColor: 'white',
//     accidental: null,
//     noteStatus: 'incorrect',
//   },
//   {
//     noteName: 'db',
//     octave: 4,
//     keyColor: 'black',
//     accidental: 'b',
//     noteStatus: 'incorrect',
//   },
//   { noteName: 'd', octave: 4, keyColor: 'white', accidental: null },
//   { noteName: 'eb', octave: 4, keyColor: 'black', accidental: 'b' },
//   { noteName: 'e', octave: 4, keyColor: 'white', accidental: null },
//   { noteName: 'f', octave: 4, keyColor: 'white', accidental: null },
//   { noteName: 'gb', octave: 4, keyColor: 'black', accidental: 'b' },
//   { noteName: 'g', octave: 4, keyColor: 'white', accidental: null },
//   { noteName: 'ab', octave: 4, keyColor: 'black', accidental: 'b' },
//   { noteName: 'a', octave: 4, keyColor: 'white', accidental: null },
//   { noteName: 'bb', octave: 4, keyColor: 'black', accidental: 'b' },
//   { noteName: 'b', octave: 5, keyColor: 'white', accidental: null },
// ];
