import { Note } from './note';

export const keyboardNotes: Note[] = [
  {
    id: 1,
    noteName: 'c',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'c',
    altAccidental: null,
  },
  {
    id: 2,
    noteName: 'c#',
    octave: 4,
    keyColor: 'black',
    accidental: '#',
    noteStatus: 'incorrect',
    altNote: 'd',
    altAccidental: 'b',
  },
  {
    id: 3,
    noteName: 'd',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'd',
    altAccidental: null,
  },
  {
    id: 4,
    noteName: 'd#',
    octave: 4,
    keyColor: 'black',
    accidental: '#',
    noteStatus: 'incorrect',
    altNote: 'e',
    altAccidental: 'b',
  },
  {
    id: 5,
    noteName: 'e',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'e',
    altAccidental: null,
  },
  {
    id: 6,
    noteName: 'f',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'f',
    altAccidental: null,
  },
  {
    id: 7,
    noteName: 'f#',
    octave: 4,
    keyColor: 'black',
    accidental: '#',
    noteStatus: 'incorrect',
    altNote: 'g',
    altAccidental: 'b',
  },
  {
    id: 8,
    noteName: 'g',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'g',
    altAccidental: null,
  },
  {
    id: 9,
    noteName: 'g#',
    octave: 4,
    keyColor: 'black',
    accidental: '#',
    noteStatus: 'incorrect',
    altNote: 'a',
    altAccidental: 'b',
  },
  {
    id: 10,
    noteName: 'a',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'a',
    altAccidental: null,
  },
  {
    id: 11,
    noteName: 'a#',
    octave: 4,
    keyColor: 'black',
    accidental: '#',
    noteStatus: 'incorrect',
    altNote: 'b',
    altAccidental: 'b',
  },
  {
    id: 12,
    noteName: 'b',
    octave: 4,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'b',
    altAccidental: null,
  },
  {
    id: 13,
    noteName: 'c',
    octave: 5,
    keyColor: 'white',
    accidental: null,
    noteStatus: 'incorrect',
    altNote: 'c',
    altAccidental: null,
  },
];
